Dz
VictorRmgn/qa-automation-java pull request #6
Opened 2021-09-07 12:28 UTC by VictorRmgn

@IgorSklyar  Посмотри пожалуйста как будет время 5 задание

2021-09-07 17:00 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
>          //log request
удали плиз комментарии

2021-09-07 17:01 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/app/LoanCalcController.java
>          //log request
удали плиз комментарии

2021-09-07 17:02 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/app/LoanCalcService.java
>          // расчеты
и здесь)

2021-09-07 17:16 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +        final int localVar = ++requestId;
для чего создаешь переменную localVar?  можно просто записать так:   return ++requestId;

2021-09-07 17:17 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +       // int requestId = createRequest();
не нужная строка?)

2021-09-07 17:19 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
>          System.out.println(requestId + " mast be 1");
must

2021-09-07 17:42 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +        LoanRequest request = new LoanRequest(LoanType.PERSON, 10, 2000);
Можно сделать static import  для PERSON

2021-09-07 17:50 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/app/LoanCalcLog.java
> +    public static void log(LoanRequest request) {
переменная  request нигде не используется

2021-09-07 17:54 UTC, IgorSklyar requested changes
Привет. Ты верно выполнил задание, все хорошо,  при этом есть несколько замечаний, которые необходимо поправить. Пройдись  пожалуйста по всему проекту и подчисть лишние комментарии в коде, плюс еще некоторе моменты что я указал

2021-09-08 04:02 UTC, VictorRmgn commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +        LoanRequest request = new LoanRequest(LoanType.PERSON, 10, 2000);
а enum разве сам по себе не static?

2021-09-08 07:05 UTC, IgorSklyar commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +        LoanRequest request = new LoanRequest(LoanType.PERSON, 10, 2000);
да, и поэтому можно сделать import  static com.tinkoff.edu.app. LoanType.*; 
и вместо LoanType.PERSON оставить просто PERSON )

2021-09-08 11:41 UTC, VictorRmgn commented
@IgorSklyar  добавил, вроде всё, но это не точно .. ((

2021-09-08 11:59 UTC, IgorSklyar commented
@VictorRmgn  кажется  забыл про LoanCalcLog.java )

2021-09-08 12:42 UTC, IgorSklyar approved these changes
все ок! так держать )

2021-09-08 12:42 UTC, merged